services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: loan-sqlserver
    environment:
      SA_PASSWORD: "WowReallyStrongPassword0001"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - loan-network

networks:
  loan-network:
    driver: bridge